### PR TITLE
Update `symfony/filesystem` to `^3.0`

### PR DESCRIPTION
**Pull request by abenevaut**
Regular package update for `symfony/filesystem`

### CODE REVIEW

**Comment by lucatume** [comment]
Thanks for the pull request. I will need to try this out in wp-browser before committing though.

**Comment by abenevaut** [comment]
I will try it on my side this weekend, i will let's you know if everything is alright or (if i have time) propose a PR on https://github.com/lucatume/wp-browser repo.

**Comment by lucatume** [comment]
Many thanks.

**Comment by abenevaut** [comment]
I finally had time to test this vendor with `wp-browser`, looks working fine!

- https://github.com/42antoine/wp-browser (have a look to the dependence integration there : https://github.com/42antoine/wp-browser/blob/update-wp-browser-commons/composer.json)
- https://travis-ci.org/42antoine/wp-browser/builds/415526445

**Comment by abenevaut** [comment]
I'm now fixing nightly tests.

**Comment by lucatume** [comment]
Thanks!

**Pull request merged**
